# Generated by Django 6.0.6 on 2026-06-25 17:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('earnings_to_date', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_reg', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imported File',
                'verbose_name_plural': 'Imported Files',
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=32, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
            },
        ),
        migrations.CreateModel(
            name='Prs_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Client_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Payee_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Payee_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Song_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Song_Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Composers', models.TextField(blank=True, null=True)),
                ('Source_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Source_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Income_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Income_Type_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Main_Income_Type_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Catalogue_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Income_Period', models.CharField(blank=True, max_length=50, null=True)),
                ('Units', models.IntegerField(default=0)),
                ('Percentage_Collected_by_BMG', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Amount_Collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('Royalty_Payout_Percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Royalty_Payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('Statement_ID_Year', models.PositiveIntegerField(default=0)),
                ('Statement_ID_Number', models.PositiveIntegerField(default=0)),
                ('Domestic_Or_Foreign_Source_Indicator', models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('Foreign', 'Foreign'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('Foreign_Source', models.CharField(blank=True, max_length=255, null=True)),
                ('Royalty_Country_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Royalty_Country_Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Artist', models.CharField(blank=True, max_length=255, null=True)),
                ('ISRC', models.CharField(blank=True, max_length=12, null=True)),
                ('Album_Or_Production', models.CharField(blank=True, max_length=255, null=True)),
                ('Episode', models.CharField(blank=True, max_length=255, null=True)),
                ('Licence_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Original_Source_As_Received', models.CharField(blank=True, max_length=255, null=True)),
                ('Original_Source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'PRS Data',
                'verbose_name_plural': 'PRS Data Records',
                'indexes': [models.Index(fields=['Client_Code'], name='artist_logs_Client__464268_idx'), models.Index(fields=['Song_Code'], name='artist_logs_Song_Co_4bf162_idx'), models.Index(fields=['Income_Period'], name='artist_logs_Income__b7df10_idx'), models.Index(fields=['ISRC'], name='artist_logs_ISRC_1cb710_idx')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_logs.artist')),
            ],
        ),
    ]
