# Generated by Django 6.0.6 on 2026-07-07 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('isrc', models.CharField(blank=True, max_length=12, null=True)),
                ('earnings_to_date', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_reg', models.CharField(default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('main_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(max_length=50, unique=True)),
                ('statement_date', models.DateField()),
                ('start_period', models.CharField(help_text='Start of the income period (e.g., 202501)', max_length=20)),
                ('end_period', models.CharField(help_text='End of the income period (e.g., 202506)', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_domestic', models.BooleanField(default=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_source', models.CharField(blank=True, max_length=255, null=True)),
                ('foreign_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('catalogue_number', models.CharField(blank=True, max_length=50, null=True)),
                ('isrc', models.CharField(blank=True, max_length=12, null=True)),
                ('album_or_production', models.CharField(blank=True, max_length=255, null=True)),
                ('episode', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='songs', to='artist_logs.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Prs_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(db_index=True, max_length=255)),
                ('song_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('source_code', models.CharField(blank=True, max_length=20, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('domestic_or_foreign', models.CharField(blank=True, choices=[('D', 'Domestic'), ('F', 'Foreign')], max_length=1, null=True)),
                ('foreign_source', models.CharField(blank=True, max_length=255, null=True)),
                ('royalty_country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('royalty_country_description', models.CharField(blank=True, max_length=100, null=True)),
                ('income_type_code', models.CharField(blank=True, max_length=20, null=True)),
                ('income_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('main_income_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('royalty_payout_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('royalty_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statement_id_year', models.CharField(blank=True, max_length=10, null=True)),
                ('statement_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('income_period', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('catalogue_no', models.CharField(blank=True, max_length=50, null=True)),
                ('composers', models.TextField(blank=True, null=True)),
                ('original_source_as_received', models.CharField(blank=True, max_length=100, null=True)),
                ('original_source', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('isrc', models.CharField(blank=True, max_length=12, null=True)),
                ('album_or_production', models.CharField(blank=True, max_length=255, null=True)),
                ('episode', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_logs.incometype')),
                ('payment_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_records', to='artist_logs.paymentstatement')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_records', to='artist_logs.song')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_logs.source')),
            ],
            options={
                'verbose_name': 'PRS Data Record',
                'verbose_name_plural': 'PRS Data Records',
                'ordering': ['-income_period', 'song_title'],
                'unique_together': {('song_code', 'income_period', 'source_code', 'income_type_code')},
            },
        ),
    ]
