# Generated by Django 6.0.6 on 2026-07-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_sort_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_threshold', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum amount (£) before payment is issued', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composer',
                'verbose_name_plural': 'Composers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='incometype',
            options={'ordering': ['name'], 'verbose_name': 'Income Type', 'verbose_name_plural': 'Income Types'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatement',
            options={'ordering': ['-statement_date'], 'verbose_name': 'Payment Statement', 'verbose_name_plural': 'Payment Statements'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterModelOptions(
            name='uploadhistory',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Upload History', 'verbose_name_plural': 'Upload Histories'},
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs_legacy', to='artist_logs.artist'),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the upload failed', null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_hash',
            field=models.CharField(help_text='MD5 hash of the file content for duplicate detection', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_name',
            field=models.CharField(help_text='Original name of the uploaded file', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='records_imported',
            field=models.IntegerField(default=0, help_text='Number of records successfully imported from this file'),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Partial', 'Partial')], default='Success', help_text='Status of the upload (Success/Failed/Partial)', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['song_title'], name='artist_logs_song_ti_2eb56c_idx'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['income_period'], name='artist_logs_income__f72553_idx'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['is_paid'], name='artist_logs_is_paid_afd3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['payment_statement'], name='artist_logs_payment_00b838_idx'),
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='artist_logs.composer'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code',), name='unique_song_code'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='artist_logs.composer'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='payment_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='artist_logs.paymentstatement'),
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.UniqueConstraint(fields=('composer', 'payment_statement'), name='unique_payment_plan_per_composer_per_statement'),
        ),
    ]
