# Generated by Django 6.0.6 on 2026-06-25 17:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prs_data',
            name='Amount_Collected',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='Percentage_Collected_by_BMG',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='Royalty_Payable',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='Royalty_Payout_Percentage',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='Statement_ID_Number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='Statement_ID_Year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='Units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
