# Generated by Django 6.0.6 on 2026-07-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(condition=models.Q(('composer__isnull', False)), fields=('composer', 'title'), name='unique_song_title_per_composer'),
        ),
    ]
