# Generated by Django 6.0.6 on 2026-07-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0002_song_unique_song_title_per_composer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to temporary file for AJAX uploads', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the file was processed', null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed'), ('Partial', 'Partial')], default='Pending', help_text='Status of the upload (Pending/Processing/Success/Failed/Partial)', max_length=50),
        ),
    ]
