# Generated by Django 6.0.6 on 2026-07-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0003_uploadhistory_file_path_uploadhistory_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prs_data',
            unique_together=set(),
        ),
    ]
