# Generated by Django 6.0.6 on 2026-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0003_client_payee_artist_name_prs_data_composers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='compositions', to='artist_logs.artist'),
        ),
    ]
