# Generated by Django 6.0.6 on 2026-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0004_remove_track_artist_alter_prs_data_composers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
