# Generated by Django 6.0.6 on 2026-07-12 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0004_alter_prs_data_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of royalties for this composer (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, help_text="Additional notes about this composer's contribution", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Song Composer Split',
                'verbose_name_plural': 'Song Composer Splits',
                'ordering': ['song', 'composer'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_title_per_composer',
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, help_text='Legacy: The primary composer of this song (for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='artist_logs.composer'),
        ),
        migrations.AddField(
            model_name='songcomposer',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_composers', to='artist_logs.composer'),
        ),
        migrations.AddField(
            model_name='songcomposer',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_composers', to='artist_logs.song'),
        ),
        migrations.AlterUniqueTogether(
            name='songcomposer',
            unique_together={('song', 'composer')},
        ),
    ]
