# Generated by Django 6.0.6 on 2026-07-12 14:51

import artist_logs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0005_songcomposer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prs_data',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata for this PRS record', null=True),
        ),
        migrations.AddField(
            model_name='prs_data',
            name='tags',
            field=artist_logs.fields.ListField(blank=True, help_text='Tags for categorizing this PRS record', null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='domestic_or_foreign',
            field=models.CharField(blank=True, choices=[('D', 'Domestic'), ('F', 'Foreign')], db_index=True, help_text='Whether the source is domestic or foreign', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='income_type_code',
            field=models.CharField(blank=True, db_index=True, help_text='Code of the income type (denormalized from IncomeType)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been paid'),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='isrc',
            field=models.CharField(blank=True, db_index=True, help_text='International Standard Recording Code', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when the payment was made', null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='royalty_country_code',
            field=models.CharField(blank=True, db_index=True, help_text='Country code for the royalty source', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='royalty_payable',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Amount payable to the composer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='source_code',
            field=models.CharField(blank=True, db_index=True, help_text='Code of the source (denormalized from Source)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='statement_id_year',
            field=models.CharField(blank=True, db_index=True, help_text='Year part of the statement ID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='catalogue_number',
            field=models.CharField(blank=True, db_index=True, help_text='Catalogue number of the song', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Unique code for the song (e.g., '6087301')", max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this song was created'),
        ),
        migrations.AlterField(
            model_name='song',
            name='isrc',
            field=models.CharField(blank=True, db_index=True, help_text='International Standard Recording Code', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, help_text="Title of the song (e.g., 'Dank')", max_length=255),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['song', 'income_period'], name='artist_logs_song_id_0a7a74_idx'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['source', 'income_period'], name='artist_logs_source__e0ecd9_idx'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['income_type', 'income_period'], name='artist_logs_income__62eec1_idx'),
        ),
        migrations.AddIndex(
            model_name='prs_data',
            index=models.Index(fields=['-created_at'], name='artist_logs_created_e38157_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='song_title_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['code'], name='song_code_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['catalogue_number'], name='song_catalogue_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['isrc'], name='song_isrc_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at'], name='song_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='prs_data',
            constraint=models.UniqueConstraint(condition=models.Q(('song_code__isnull', False), ('income_period__isnull', False), ('source_code__isnull', False), ('income_type_code__isnull', False)), fields=('song_code', 'income_period', 'source_code', 'income_type_code'), name='unique_prs_record'),
        ),
    ]
