# Generated by Django 6.0.6 on 2026-07-13 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0006_prs_data_metadata_prs_data_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='file_path',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='records_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_hash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='processed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='records_imported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Partial', 'Partial'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
