# Generated by Django 6.0.6 on 2026-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0007_remove_uploadhistory_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prs_data',
            name='royalty_country_code',
            field=models.CharField(blank=True, db_index=True, help_text='Country code for the royalty source', max_length=4, null=True),
        ),
    ]
