# Generated by Django 6.0.6 on 2026-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0008_alter_prs_data_royalty_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songcomposer',
            options={'ordering': ['song', '-split_percentage'], 'verbose_name': 'Song Composer Split', 'verbose_name_plural': 'Song Composer Splits'},
        ),
        migrations.AlterField(
            model_name='song',
            name='isrc',
            field=models.CharField(blank=True, help_text='International Standard Recording Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the song', max_length=255),
        ),
    ]
