# Generated by Django 6.0.6 on 2026-07-14 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0009_alter_songcomposer_options_alter_song_isrc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomposer',
            name='split_percentage',
            field=models.FloatField(help_text='Percentage of royalties for this composer (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
