# Generated by Django 6.0.6 on 2026-07-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0010_alter_songcomposer_split_percentage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prs_data',
            name='unique_prs_record',
        ),
        migrations.RemoveIndex(
            model_name='prs_data',
            name='artist_logs_is_paid_afd3fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='prs_data',
            name='artist_logs_payment_00b838_idx',
        ),
        migrations.RemoveIndex(
            model_name='prs_data',
            name='artist_logs_song_id_0a7a74_idx',
        ),
        migrations.RemoveIndex(
            model_name='prs_data',
            name='artist_logs_source__e0ecd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='prs_data',
            name='artist_logs_income__62eec1_idx',
        ),
        migrations.RemoveIndex(
            model_name='prs_data',
            name='artist_logs_created_e38157_idx',
        ),
        migrations.AlterField(
            model_name='prs_data',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_data_records', to='artist_logs.song'),
        ),
    ]
