# Generated by Django 6.0.6 on 2026-07-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_logs', '0011_remove_prs_data_unique_prs_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prs_data',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_records', to='artist_logs.song'),
        ),
    ]
